//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectedServices_SKATForwardEIndkomstService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.kombit.dk/2017/01/01/", ConfigurationName="ConnectedServices_SKATForwardEIndkomstService.SKATForwardEIndkomstServiceServiceP" +
        "ortType")]
    public interface SKATForwardEIndkomstServiceServicePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kombit.dk/2017/01/01/SKATForwardEIndkomstServiceService_4#SF0770_A_Ind" +
            "komstoplysningerLaes_IndkomstoplysningerLaes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndkomstOplysningPersonHent_OType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndkomstOplysningPersonHent_IType))]
        System.Threading.Tasks.Task<ConnectedServices_SKATForwardEIndkomstService.IndkomstOplysningPersonHent1> SF0770_A_IndkomstoplysningerLaes_IndkomstoplysningerLaesAsync(ConnectedServices_SKATForwardEIndkomstService.IndkomstOplysningPersonHent request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.kombit.dk/2017/01/01/")]
    public partial class IndkomstOplysningPersonHent_I : IndkomstOplysningPersonHent_IType
    {
        
        private string revisionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string revision
        {
            get
            {
                return this.revisionField;
            }
            set
            {
                this.revisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kombit.dk/2017/01/01/")]
    public partial class IndkomstOplysningPersonHent_IType
    {
        
        private HovedOplysningerType hovedOplysningerField;
        
        private IndkomstOplysningPersonInddataType indkomstOplysningPersonInddataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://kombit.dk/xml/schemas/kontekst/2017/01/01/", Order=0)]
        public HovedOplysningerType HovedOplysninger
        {
            get
            {
                return this.hovedOplysningerField;
            }
            set
            {
                this.hovedOplysningerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IndkomstOplysningPersonInddataType IndkomstOplysningPersonInddata
        {
            get
            {
                return this.indkomstOplysningPersonInddataField;
            }
            set
            {
                this.indkomstOplysningPersonInddataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kombit.dk/xml/schemas/kontekst/2017/01/01/")]
    public partial class HovedOplysningerType
    {
        
        private string transaktionsIdField;
        
        private System.DateTime transaktionsTidField;
        
        private string onBehalfOfUserField;
        
        private string callersServiceCallIdentifierField;
        
        private string accountingInfoField;
        
        private AuthorityContextType authorityContextField;
        
        private RuteType ruteField;
        
        private System.Xml.XmlElement[] processingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransaktionsId
        {
            get
            {
                return this.transaktionsIdField;
            }
            set
            {
                this.transaktionsIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime TransaktionsTid
        {
            get
            {
                return this.transaktionsTidField;
            }
            set
            {
                this.transaktionsTidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OnBehalfOfUser
        {
            get
            {
                return this.onBehalfOfUserField;
            }
            set
            {
                this.onBehalfOfUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CallersServiceCallIdentifier
        {
            get
            {
                return this.callersServiceCallIdentifierField;
            }
            set
            {
                this.callersServiceCallIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AccountingInfo
        {
            get
            {
                return this.accountingInfoField;
            }
            set
            {
                this.accountingInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public AuthorityContextType AuthorityContext
        {
            get
            {
                return this.authorityContextField;
            }
            set
            {
                this.authorityContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public RuteType Rute
        {
            get
            {
                return this.ruteField;
            }
            set
            {
                this.ruteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Processing", Order=7)]
        public System.Xml.XmlElement[] Processing
        {
            get
            {
                return this.processingField;
            }
            set
            {
                this.processingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kombit.dk/xml/schemas/kontekst/2017/01/01/")]
    public partial class AuthorityContextType
    {
        
        private string municipalityCVRField;
        
        /// <remarks/>
        public string MunicipalityCVR
        {
            get
            {
                return this.municipalityCVRField;
            }
            set
            {
                this.municipalityCVRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class VirksomhedLoenPeriodeStrukturType
    {
        
        private string angivelseVirksomhedEgenIdentifikatorField;
        
        private AngivelsePeriodeStrukturType angivelsePeriodeStrukturField;
        
        private string ansaettelseforholdMedarbejderIdentifikatorField;
        
        private System.DateTime indkomstPersonGruppeDispositionDatoField;
        
        private bool indkomstPersonGruppeDispositionDatoFieldSpecified;
        
        private AngivelseBlanketIndholdStrukturType angivelseBlanketIndholdStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/angivelse/xml/schemas/20071202/", Order=0)]
        public string AngivelseVirksomhedEgenIdentifikator
        {
            get
            {
                return this.angivelseVirksomhedEgenIdentifikatorField;
            }
            set
            {
                this.angivelseVirksomhedEgenIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AngivelsePeriodeStrukturType AngivelsePeriodeStruktur
        {
            get
            {
                return this.angivelsePeriodeStrukturField;
            }
            set
            {
                this.angivelsePeriodeStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/ansaettelseforhold/xml/schemas/20071202" +
            "/", Order=2)]
        public string AnsaettelseforholdMedarbejderIdentifikator
        {
            get
            {
                return this.ansaettelseforholdMedarbejderIdentifikatorField;
            }
            set
            {
                this.ansaettelseforholdMedarbejderIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/indkomstpersongruppe/xml/schemas/200712" +
            "02/", DataType="date", Order=3)]
        public System.DateTime IndkomstPersonGruppeDispositionDato
        {
            get
            {
                return this.indkomstPersonGruppeDispositionDatoField;
            }
            set
            {
                this.indkomstPersonGruppeDispositionDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndkomstPersonGruppeDispositionDatoSpecified
        {
            get
            {
                return this.indkomstPersonGruppeDispositionDatoFieldSpecified;
            }
            set
            {
                this.indkomstPersonGruppeDispositionDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public AngivelseBlanketIndholdStrukturType AngivelseBlanketIndholdStruktur
        {
            get
            {
                return this.angivelseBlanketIndholdStrukturField;
            }
            set
            {
                this.angivelseBlanketIndholdStrukturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AngivelsePeriodeStrukturType
    {
        
        private DateIntervalType angivelsePeriodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/angivelse/xml/schemas/20071202/", Order=0)]
        public DateIntervalType AngivelsePeriode
        {
            get
            {
                return this.angivelsePeriodeField;
            }
            set
            {
                this.angivelsePeriodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2007/09/01/")]
    public partial class DateIntervalType
    {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StartDate", typeof(System.DateTime), Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2006/09/01/", DataType="date", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("EndDate", typeof(System.DateTime), Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2007/04/15/", DataType="date", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DurationMeasure", typeof(string), DataType="duration", Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2007/09/01/", IncludeInSchema=false)]
    public enum ItemsChoiceType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://rep.oio.dk/xkom.dk/xml/schemas/2006/09/01/:StartDate")]
        StartDate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://rep.oio.dk/xkom.dk/xml/schemas/2007/04/15/:EndDate")]
        EndDate,
        
        /// <remarks/>
        DurationMeasure,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AngivelseBlanketIndholdStrukturType
    {
        
        private AngivelseNiveau1Type[] angivelseOplysningSamlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AngivelseNiveau1", IsNullable=false)]
        public AngivelseNiveau1Type[] AngivelseOplysningSamling
        {
            get
            {
                return this.angivelseOplysningSamlingField;
            }
            set
            {
                this.angivelseOplysningSamlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AngivelseNiveau1Type
    {
        
        private string blanketNummerIdentifikatorField;
        
        private AngivelseFeltIndholdStrukturType[] angivelseFeltSamlingField;
        
        private AngivelseNiveau2Type[] underAngivelseSamlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/blanket/xml/schemas/20071202/", Order=0)]
        public string BlanketNummerIdentifikator
        {
            get
            {
                return this.blanketNummerIdentifikatorField;
            }
            set
            {
                this.blanketNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AngivelseFeltIndholdStruktur", IsNullable=false)]
        public AngivelseFeltIndholdStrukturType[] AngivelseFeltSamling
        {
            get
            {
                return this.angivelseFeltSamlingField;
            }
            set
            {
                this.angivelseFeltSamlingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AngivelseNiveau2", IsNullable=false)]
        public AngivelseNiveau2Type[] UnderAngivelseSamling
        {
            get
            {
                return this.underAngivelseSamlingField;
            }
            set
            {
                this.underAngivelseSamlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AngivelseFeltIndholdStrukturType
    {
        
        private BlanketFeltEnhedStrukturType blanketFeltEnhedStrukturField;
        
        private string angivelseFeltIndholdTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BlanketFeltEnhedStrukturType BlanketFeltEnhedStruktur
        {
            get
            {
                return this.blanketFeltEnhedStrukturField;
            }
            set
            {
                this.blanketFeltEnhedStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/angivelsefelt/xml/schemas/20071202/", Order=1)]
        public string AngivelseFeltIndholdTekst
        {
            get
            {
                return this.angivelseFeltIndholdTekstField;
            }
            set
            {
                this.angivelseFeltIndholdTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class BlanketFeltEnhedStrukturType
    {
        
        private string blanketFeltNummerIdentifikatorField;
        
        private string feltEnhedTypeKodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/blanketfelt/xml/schemas/20071202/", DataType="integer", Order=0)]
        public string BlanketFeltNummerIdentifikator
        {
            get
            {
                return this.blanketFeltNummerIdentifikatorField;
            }
            set
            {
                this.blanketFeltNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/feltenhedtype/xml/schemas/20071202/", DataType="integer", Order=1)]
        public string FeltEnhedTypeKode
        {
            get
            {
                return this.feltEnhedTypeKodeField;
            }
            set
            {
                this.feltEnhedTypeKodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AngivelseNiveau2Type
    {
        
        private string blanketNummerIdentifikatorField;
        
        private AngivelseFeltIndholdStrukturType[] angivelseFeltSamlingField;
        
        private AngivelseNiveau3Type[] underAngivelseSamlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/blanket/xml/schemas/20071202/", Order=0)]
        public string BlanketNummerIdentifikator
        {
            get
            {
                return this.blanketNummerIdentifikatorField;
            }
            set
            {
                this.blanketNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AngivelseFeltIndholdStruktur", IsNullable=false)]
        public AngivelseFeltIndholdStrukturType[] AngivelseFeltSamling
        {
            get
            {
                return this.angivelseFeltSamlingField;
            }
            set
            {
                this.angivelseFeltSamlingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AngivelseNiveau3", IsNullable=false)]
        public AngivelseNiveau3Type[] UnderAngivelseSamling
        {
            get
            {
                return this.underAngivelseSamlingField;
            }
            set
            {
                this.underAngivelseSamlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AngivelseNiveau3Type
    {
        
        private string blanketNummerIdentifikatorField;
        
        private AngivelseFeltIndholdStrukturType[] angivelseFeltSamlingField;
        
        private AngivelseNiveau4Type[] underAngivelseSamlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/blanket/xml/schemas/20071202/", Order=0)]
        public string BlanketNummerIdentifikator
        {
            get
            {
                return this.blanketNummerIdentifikatorField;
            }
            set
            {
                this.blanketNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AngivelseFeltIndholdStruktur", IsNullable=false)]
        public AngivelseFeltIndholdStrukturType[] AngivelseFeltSamling
        {
            get
            {
                return this.angivelseFeltSamlingField;
            }
            set
            {
                this.angivelseFeltSamlingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AngivelseNiveau4", IsNullable=false)]
        public AngivelseNiveau4Type[] UnderAngivelseSamling
        {
            get
            {
                return this.underAngivelseSamlingField;
            }
            set
            {
                this.underAngivelseSamlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AngivelseNiveau4Type
    {
        
        private string blanketNummerIdentifikatorField;
        
        private AngivelseFeltIndholdStrukturType[] angivelseFeltSamlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/blanket/xml/schemas/20071202/", Order=0)]
        public string BlanketNummerIdentifikator
        {
            get
            {
                return this.blanketNummerIdentifikatorField;
            }
            set
            {
                this.blanketNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AngivelseFeltIndholdStruktur", IsNullable=false)]
        public AngivelseFeltIndholdStrukturType[] AngivelseFeltSamling
        {
            get
            {
                return this.angivelseFeltSamlingField;
            }
            set
            {
                this.angivelseFeltSamlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningVirksomhedStrukturType
    {
        
        private IndberetningForVirksomhedStrukturType indberetningForVirksomhedStrukturField;
        
        private string indkomstOplysningAdgangReferenceNummerIdentifikatorField;
        
        private IndkomstOplysningVirksomhedStrukturTypeIndberetningPligtigVirksomhed[] indkomstOplysningVirksomhedSamlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IndberetningForVirksomhedStrukturType IndberetningForVirksomhedStruktur
        {
            get
            {
                return this.indberetningForVirksomhedStrukturField;
            }
            set
            {
                this.indberetningForVirksomhedStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/indkomstoplysningadgangreferencenummer/" +
            "xml/schemas/20071202/", Order=1)]
        public string IndkomstOplysningAdgangReferenceNummerIdentifikator
        {
            get
            {
                return this.indkomstOplysningAdgangReferenceNummerIdentifikatorField;
            }
            set
            {
                this.indkomstOplysningAdgangReferenceNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IndberetningPligtigVirksomhed", IsNullable=false)]
        public IndkomstOplysningVirksomhedStrukturTypeIndberetningPligtigVirksomhed[] IndkomstOplysningVirksomhedSamling
        {
            get
            {
                return this.indkomstOplysningVirksomhedSamlingField;
            }
            set
            {
                this.indkomstOplysningVirksomhedSamlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndberetningForVirksomhedStrukturType
    {
        
        private IndberetningForVirksomhedStrukturTypeIndberetningForVirksomhed indberetningForVirksomhedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IndberetningForVirksomhedStrukturTypeIndberetningForVirksomhed IndberetningForVirksomhed
        {
            get
            {
                return this.indberetningForVirksomhedField;
            }
            set
            {
                this.indberetningForVirksomhedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndberetningForVirksomhedStrukturTypeIndberetningForVirksomhed
    {
        
        private string virksomhedSENummerIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/motor/class/virksomhed/xml/schemas/20080401/", Order=0)]
        public string VirksomhedSENummerIdentifikator
        {
            get
            {
                return this.virksomhedSENummerIdentifikatorField;
            }
            set
            {
                this.virksomhedSENummerIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningVirksomhedStrukturTypeIndberetningPligtigVirksomhed
    {
        
        private IndberetningPligtigVirksomhedStrukturType indberetningPligtigVirksomhedStrukturField;
        
        private VirksomhedLoenPeriodeStrukturType[] indkomstLoenPeriodeSamlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IndberetningPligtigVirksomhedStrukturType IndberetningPligtigVirksomhedStruktur
        {
            get
            {
                return this.indberetningPligtigVirksomhedStrukturField;
            }
            set
            {
                this.indberetningPligtigVirksomhedStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("VirksomhedLoenPeriodeStruktur", IsNullable=false)]
        public VirksomhedLoenPeriodeStrukturType[] IndkomstLoenPeriodeSamling
        {
            get
            {
                return this.indkomstLoenPeriodeSamlingField;
            }
            set
            {
                this.indkomstLoenPeriodeSamlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndberetningPligtigVirksomhedStrukturType
    {
        
        private IndberetningPligtigVirksomhedStrukturTypeIndberetningPligtigVirksomhed indberetningPligtigVirksomhedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IndberetningPligtigVirksomhedStrukturTypeIndberetningPligtigVirksomhed IndberetningPligtigVirksomhed
        {
            get
            {
                return this.indberetningPligtigVirksomhedField;
            }
            set
            {
                this.indberetningPligtigVirksomhedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndberetningPligtigVirksomhedStrukturTypeIndberetningPligtigVirksomhed
    {
        
        private string virksomhedSENummerIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/motor/class/virksomhed/xml/schemas/20080401/", Order=0)]
        public string VirksomhedSENummerIdentifikator
        {
            get
            {
                return this.virksomhedSENummerIdentifikatorField;
            }
            set
            {
                this.virksomhedSENummerIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
    public partial class CountryIdentificationCodeType
    {
        
        private _CountryIdentificationSchemeType schemeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public _CountryIdentificationSchemeType scheme
        {
            get
            {
                return this.schemeField;
            }
            set
            {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
    public enum _CountryIdentificationSchemeType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("iso3166-alpha2")]
        iso3166alpha2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("iso3166-alpha3")]
        iso3166alpha3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("un-numeric3")]
        unnumeric3,
        
        /// <remarks/>
        imk,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AlternativAdresseStrukturType
    {
        
        private string alternativAdresseAdresseLinie1Field;
        
        private string alternativAdresseAdresseLinie2Field;
        
        private string alternativAdresseAdresseLinie3Field;
        
        private string alternativAdresseAdresseLinie4Field;
        
        private string alternativAdresseAdresseLinie5Field;
        
        private CountryIdentificationCodeType landKodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/alternativadresse/xml/schemas/20071202/" +
            "", Order=0)]
        public string AlternativAdresseAdresseLinie1
        {
            get
            {
                return this.alternativAdresseAdresseLinie1Field;
            }
            set
            {
                this.alternativAdresseAdresseLinie1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/alternativadresse/xml/schemas/20071202/" +
            "", Order=1)]
        public string AlternativAdresseAdresseLinie2
        {
            get
            {
                return this.alternativAdresseAdresseLinie2Field;
            }
            set
            {
                this.alternativAdresseAdresseLinie2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/alternativadresse/xml/schemas/20071202/" +
            "", Order=2)]
        public string AlternativAdresseAdresseLinie3
        {
            get
            {
                return this.alternativAdresseAdresseLinie3Field;
            }
            set
            {
                this.alternativAdresseAdresseLinie3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/alternativadresse/xml/schemas/20071202/" +
            "", Order=3)]
        public string AlternativAdresseAdresseLinie4
        {
            get
            {
                return this.alternativAdresseAdresseLinie4Field;
            }
            set
            {
                this.alternativAdresseAdresseLinie4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/alternativadresse/xml/schemas/20071202/" +
            "", Order=4)]
        public string AlternativAdresseAdresseLinie5
        {
            get
            {
                return this.alternativAdresseAdresseLinie5Field;
            }
            set
            {
                this.alternativAdresseAdresseLinie5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/land/xml/schemas/20071202/", Order=5)]
        public CountryIdentificationCodeType LandKode
        {
            get
            {
                return this.landKodeField;
            }
            set
            {
                this.landKodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class SupplerendePersonOplysningStrukturType
    {
        
        private string tINIdentifikatorField;
        
        private string personNameField;
        
        private string supplerendePersonOplysningFoedselTekstField;
        
        private PersonGenderCodeType personGenderCodeField;
        
        private bool personGenderCodeFieldSpecified;
        
        private AlternativAdresseStrukturType alternativAdresseStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://eksternwiki.skat.dk/oioxml/skat_dk/eIndkomst/person/", Order=0)]
        public string TINIdentifikator
        {
            get
            {
                return this.tINIdentifikatorField;
            }
            set
            {
                this.tINIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/itst.dk/xml/schemas/2006/01/17/", Order=1)]
        public string PersonName
        {
            get
            {
                return this.personNameField;
            }
            set
            {
                this.personNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/supplerendepersonoplysning/xml/schemas/" +
            "20071202/", Order=2)]
        public string SupplerendePersonOplysningFoedselTekst
        {
            get
            {
                return this.supplerendePersonOplysningFoedselTekstField;
            }
            set
            {
                this.supplerendePersonOplysningFoedselTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2006/01/23/", Order=3)]
        public PersonGenderCodeType PersonGenderCode
        {
            get
            {
                return this.personGenderCodeField;
            }
            set
            {
                this.personGenderCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonGenderCodeSpecified
        {
            get
            {
                return this.personGenderCodeFieldSpecified;
            }
            set
            {
                this.personGenderCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public AlternativAdresseStrukturType AlternativAdresseStruktur
        {
            get
            {
                return this.alternativAdresseStrukturField;
            }
            set
            {
                this.alternativAdresseStrukturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2006/01/23/")]
    public enum PersonGenderCodeType
    {
        
        /// <remarks/>
        male,
        
        /// <remarks/>
        female,
        
        /// <remarks/>
        unspecified,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class LoenPeriodeOplysningStrukturType
    {
        
        private string angivelseVirksomhedEgenIdentifikatorField;
        
        private AngivelsePeriodeStrukturType angivelsePeriodeStrukturField;
        
        private string ansaettelseforholdMedarbejderIdentifikatorField;
        
        private System.DateTime indkomstPersonGruppeDispositionDatoField;
        
        private bool indkomstPersonGruppeDispositionDatoFieldSpecified;
        
        private SupplerendePersonOplysningStrukturType supplerendePersonOplysningStrukturField;
        
        private AngivelseBlanketIndholdStrukturType angivelseBlanketIndholdStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/angivelse/xml/schemas/20071202/", Order=0)]
        public string AngivelseVirksomhedEgenIdentifikator
        {
            get
            {
                return this.angivelseVirksomhedEgenIdentifikatorField;
            }
            set
            {
                this.angivelseVirksomhedEgenIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AngivelsePeriodeStrukturType AngivelsePeriodeStruktur
        {
            get
            {
                return this.angivelsePeriodeStrukturField;
            }
            set
            {
                this.angivelsePeriodeStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/ansaettelseforhold/xml/schemas/20071202" +
            "/", Order=2)]
        public string AnsaettelseforholdMedarbejderIdentifikator
        {
            get
            {
                return this.ansaettelseforholdMedarbejderIdentifikatorField;
            }
            set
            {
                this.ansaettelseforholdMedarbejderIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/indkomstpersongruppe/xml/schemas/200712" +
            "02/", DataType="date", Order=3)]
        public System.DateTime IndkomstPersonGruppeDispositionDato
        {
            get
            {
                return this.indkomstPersonGruppeDispositionDatoField;
            }
            set
            {
                this.indkomstPersonGruppeDispositionDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndkomstPersonGruppeDispositionDatoSpecified
        {
            get
            {
                return this.indkomstPersonGruppeDispositionDatoFieldSpecified;
            }
            set
            {
                this.indkomstPersonGruppeDispositionDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public SupplerendePersonOplysningStrukturType SupplerendePersonOplysningStruktur
        {
            get
            {
                return this.supplerendePersonOplysningStrukturField;
            }
            set
            {
                this.supplerendePersonOplysningStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public AngivelseBlanketIndholdStrukturType AngivelseBlanketIndholdStruktur
        {
            get
            {
                return this.angivelseBlanketIndholdStrukturField;
            }
            set
            {
                this.angivelseBlanketIndholdStrukturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningPersonStrukturType
    {
        
        private string personCivilRegistrationIdentifierField;
        
        private string indkomstOplysningAdgangReferenceNummerIdentifikatorField;
        
        private IndkomstOplysningPersonStrukturTypeIndberetningPligtigVirksomhed[] indkomstOplysningSamlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=0)]
        public string PersonCivilRegistrationIdentifier
        {
            get
            {
                return this.personCivilRegistrationIdentifierField;
            }
            set
            {
                this.personCivilRegistrationIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/indkomstoplysningadgangreferencenummer/" +
            "xml/schemas/20071202/", Order=1)]
        public string IndkomstOplysningAdgangReferenceNummerIdentifikator
        {
            get
            {
                return this.indkomstOplysningAdgangReferenceNummerIdentifikatorField;
            }
            set
            {
                this.indkomstOplysningAdgangReferenceNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IndberetningPligtigVirksomhed", IsNullable=false)]
        public IndkomstOplysningPersonStrukturTypeIndberetningPligtigVirksomhed[] IndkomstOplysningSamling
        {
            get
            {
                return this.indkomstOplysningSamlingField;
            }
            set
            {
                this.indkomstOplysningSamlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningPersonStrukturTypeIndberetningPligtigVirksomhed
    {
        
        private IndberetningPligtigVirksomhedStrukturType indberetningPligtigVirksomhedStrukturField;
        
        private LoenPeriodeOplysningStrukturType[] indkomstLoenPeriodeSamlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IndberetningPligtigVirksomhedStrukturType IndberetningPligtigVirksomhedStruktur
        {
            get
            {
                return this.indberetningPligtigVirksomhedStrukturField;
            }
            set
            {
                this.indberetningPligtigVirksomhedStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LoenPeriodeOplysningStruktur", IsNullable=false)]
        public LoenPeriodeOplysningStrukturType[] IndkomstLoenPeriodeSamling
        {
            get
            {
                return this.indkomstLoenPeriodeSamlingField;
            }
            set
            {
                this.indkomstLoenPeriodeSamlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstPersonUddataType
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IndkomstOplysningPersonSamling", typeof(IndkomstPersonUddataTypeIndkomstOplysningPersonSamling), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndkomstOplysningVirksomhedSamling", typeof(IndkomstPersonUddataTypeIndkomstOplysningVirksomhedSamling), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstPersonUddataTypeIndkomstOplysningPersonSamling
    {
        
        private IndkomstOplysningPersonStrukturType[] indkomstOplysningPersonStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IndkomstOplysningPersonStruktur", Order=0)]
        public IndkomstOplysningPersonStrukturType[] IndkomstOplysningPersonStruktur
        {
            get
            {
                return this.indkomstOplysningPersonStrukturField;
            }
            set
            {
                this.indkomstOplysningPersonStrukturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstPersonUddataTypeIndkomstOplysningVirksomhedSamling
    {
        
        private IndkomstOplysningVirksomhedStrukturType[] indkomstOplysningVirksomhedStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IndkomstOplysningVirksomhedStruktur", Order=0)]
        public IndkomstOplysningVirksomhedStrukturType[] IndkomstOplysningVirksomhedStruktur
        {
            get
            {
                return this.indkomstOplysningVirksomhedStrukturField;
            }
            set
            {
                this.indkomstOplysningVirksomhedStrukturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kombit.dk/xml/schemas/kontekst/2017/01/01/")]
    public partial class FejlType
    {
        
        private string fejlIdField;
        
        private string fejlTekstField;
        
        private string kildeIdField;
        
        private System.Xml.XmlElement[] identifikationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FejlId
        {
            get
            {
                return this.fejlIdField;
            }
            set
            {
                this.fejlIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FejlTekst
        {
            get
            {
                return this.fejlTekstField;
            }
            set
            {
                this.fejlTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string KildeId
        {
            get
            {
                return this.kildeIdField;
            }
            set
            {
                this.kildeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Identifikation", Order=3)]
        public System.Xml.XmlElement[] Identifikation
        {
            get
            {
                return this.identifikationField;
            }
            set
            {
                this.identifikationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kombit.dk/xml/schemas/kontekst/2017/01/01/")]
    public partial class AdvisType
    {
        
        private string advisIdField;
        
        private string advisTekstField;
        
        private string kildeIdField;
        
        private System.Xml.XmlElement[] identifikationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AdvisId
        {
            get
            {
                return this.advisIdField;
            }
            set
            {
                this.advisIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AdvisTekst
        {
            get
            {
                return this.advisTekstField;
            }
            set
            {
                this.advisTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string KildeId
        {
            get
            {
                return this.kildeIdField;
            }
            set
            {
                this.kildeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Identifikation", Order=3)]
        public System.Xml.XmlElement[] Identifikation
        {
            get
            {
                return this.identifikationField;
            }
            set
            {
                this.identifikationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kombit.dk/xml/schemas/kontekst/2017/01/01/")]
    public partial class SvarReaktionType
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Advis", typeof(AdvisType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Fejl", typeof(FejlType), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kombit.dk/xml/schemas/kontekst/2017/01/01/")]
    public partial class HovedOplysningerSvarType
    {
        
        private string transaktionsIdField;
        
        private System.DateTime transaktionsTidField;
        
        private SvarReaktionType[] svarReaktionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransaktionsId
        {
            get
            {
                return this.transaktionsIdField;
            }
            set
            {
                this.transaktionsIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime TransaktionsTid
        {
            get
            {
                return this.transaktionsTidField;
            }
            set
            {
                this.transaktionsTidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SvarReaktion", Order=2)]
        public SvarReaktionType[] SvarReaktion
        {
            get
            {
                return this.svarReaktionField;
            }
            set
            {
                this.svarReaktionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kombit.dk/2017/01/01/")]
    public partial class IndkomstOplysningPersonHent_OType
    {
        
        private HovedOplysningerSvarType hovedOplysningerSvarField;
        
        private IndkomstPersonUddataType indkomstPersonUddataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://kombit.dk/xml/schemas/kontekst/2017/01/01/", Order=0)]
        public HovedOplysningerSvarType HovedOplysningerSvar
        {
            get
            {
                return this.hovedOplysningerSvarField;
            }
            set
            {
                this.hovedOplysningerSvarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IndkomstPersonUddataType IndkomstPersonUddata
        {
            get
            {
                return this.indkomstPersonUddataField;
            }
            set
            {
                this.indkomstPersonUddataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class VirksomhedIndkomstSoegeStrukturType
    {
        
        private IndberetningForVirksomhedStrukturType indberetningForVirksomhedStrukturField;
        
        private string indkomstOplysningAdgangReferenceNummerIdentifikatorField;
        
        private IndberetningPligtigVirksomhedStrukturType indberetningPligtigVirksomhedStrukturField;
        
        private SoegePeriodeLukketStrukturType soegePeriodeLukketStrukturField;
        
        private SoegeAarMaanedLukketStrukturType soegeAarMaanedLukketStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IndberetningForVirksomhedStrukturType IndberetningForVirksomhedStruktur
        {
            get
            {
                return this.indberetningForVirksomhedStrukturField;
            }
            set
            {
                this.indberetningForVirksomhedStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/indkomstoplysningadgangreferencenummer/" +
            "xml/schemas/20071202/", Order=1)]
        public string IndkomstOplysningAdgangReferenceNummerIdentifikator
        {
            get
            {
                return this.indkomstOplysningAdgangReferenceNummerIdentifikatorField;
            }
            set
            {
                this.indkomstOplysningAdgangReferenceNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public IndberetningPligtigVirksomhedStrukturType IndberetningPligtigVirksomhedStruktur
        {
            get
            {
                return this.indberetningPligtigVirksomhedStrukturField;
            }
            set
            {
                this.indberetningPligtigVirksomhedStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SoegePeriodeLukketStrukturType SoegePeriodeLukketStruktur
        {
            get
            {
                return this.soegePeriodeLukketStrukturField;
            }
            set
            {
                this.soegePeriodeLukketStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public SoegeAarMaanedLukketStrukturType SoegeAarMaanedLukketStruktur
        {
            get
            {
                return this.soegeAarMaanedLukketStrukturField;
            }
            set
            {
                this.soegeAarMaanedLukketStrukturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class SoegePeriodeLukketStrukturType
    {
        
        private DateIntervalType dateIntervalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2007/09/01/", Order=0)]
        public DateIntervalType DateInterval
        {
            get
            {
                return this.dateIntervalField;
            }
            set
            {
                this.dateIntervalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class SoegeAarMaanedLukketStrukturType
    {
        
        private string soegeAarMaanedFraKodeField;
        
        private string soegeAarMaanedTilKodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/soegeaarmaanedfrakode/xml/schemas/20071" +
            "202/", DataType="integer", Order=0)]
        public string SoegeAarMaanedFraKode
        {
            get
            {
                return this.soegeAarMaanedFraKodeField;
            }
            set
            {
                this.soegeAarMaanedFraKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/soegeaarmaanedtilkode/xml/schemas/20071" +
            "202/", DataType="integer", Order=1)]
        public string SoegeAarMaanedTilKode
        {
            get
            {
                return this.soegeAarMaanedTilKodeField;
            }
            set
            {
                this.soegeAarMaanedTilKodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class PersonIndkomstSoegeStrukturType
    {
        
        private string personCivilRegistrationIdentifierField;
        
        private string indkomstOplysningAdgangReferenceNummerIdentifikatorField;
        
        private IndberetningPligtigVirksomhedStrukturType indberetningPligtigVirksomhedStrukturField;
        
        private SoegePeriodeLukketStrukturType soegePeriodeLukketStrukturField;
        
        private SoegeAarMaanedLukketStrukturType soegeAarMaanedLukketStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=0)]
        public string PersonCivilRegistrationIdentifier
        {
            get
            {
                return this.personCivilRegistrationIdentifierField;
            }
            set
            {
                this.personCivilRegistrationIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/indkomstoplysningadgangreferencenummer/" +
            "xml/schemas/20071202/", Order=1)]
        public string IndkomstOplysningAdgangReferenceNummerIdentifikator
        {
            get
            {
                return this.indkomstOplysningAdgangReferenceNummerIdentifikatorField;
            }
            set
            {
                this.indkomstOplysningAdgangReferenceNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public IndberetningPligtigVirksomhedStrukturType IndberetningPligtigVirksomhedStruktur
        {
            get
            {
                return this.indberetningPligtigVirksomhedStrukturField;
            }
            set
            {
                this.indberetningPligtigVirksomhedStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SoegePeriodeLukketStrukturType SoegePeriodeLukketStruktur
        {
            get
            {
                return this.soegePeriodeLukketStrukturField;
            }
            set
            {
                this.soegePeriodeLukketStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public SoegeAarMaanedLukketStrukturType SoegeAarMaanedLukketStruktur
        {
            get
            {
                return this.soegeAarMaanedLukketStrukturField;
            }
            set
            {
                this.soegeAarMaanedLukketStrukturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AbonnentVirksomhedStrukturType
    {
        
        private AbonnentVirksomhedStrukturTypeAbonnentVirksomhed abonnentVirksomhedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AbonnentVirksomhedStrukturTypeAbonnentVirksomhed AbonnentVirksomhed
        {
            get
            {
                return this.abonnentVirksomhedField;
            }
            set
            {
                this.abonnentVirksomhedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AbonnentVirksomhedStrukturTypeAbonnentVirksomhed
    {
        
        private string virksomhedSENummerIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/motor/class/virksomhed/xml/schemas/20080401/", Order=0)]
        public string VirksomhedSENummerIdentifikator
        {
            get
            {
                return this.virksomhedSENummerIdentifikatorField;
            }
            set
            {
                this.virksomhedSENummerIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AbonnentStrukturType
    {
        
        private AbonnentVirksomhedStrukturType abonnentVirksomhedStrukturField;
        
        private string indkomstOplysningAdgangMedarbejderIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AbonnentVirksomhedStrukturType AbonnentVirksomhedStruktur
        {
            get
            {
                return this.abonnentVirksomhedStrukturField;
            }
            set
            {
                this.abonnentVirksomhedStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/indkomstoplysningadgangmedarbejderident" +
            "ifikator/xml/schemas/20071202/", Order=1)]
        public string IndkomstOplysningAdgangMedarbejderIdentifikator
        {
            get
            {
                return this.indkomstOplysningAdgangMedarbejderIdentifikatorField;
            }
            set
            {
                this.indkomstOplysningAdgangMedarbejderIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AbonnentAdgangStrukturType
    {
        
        private string abonnentTypeKodeField;
        
        private string abonnementTypeKodeField;
        
        private string adgangFormaalTypeKodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/abonnenttype/xml/schemas/20071202/", DataType="integer", Order=0)]
        public string AbonnentTypeKode
        {
            get
            {
                return this.abonnentTypeKodeField;
            }
            set
            {
                this.abonnentTypeKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/abonnementtype/xml/schemas/20071202/", DataType="integer", Order=1)]
        public string AbonnementTypeKode
        {
            get
            {
                return this.abonnementTypeKodeField;
            }
            set
            {
                this.abonnementTypeKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/adgangformaaltype/xml/schemas/20071202/" +
            "", DataType="integer", Order=2)]
        public string AdgangFormaalTypeKode
        {
            get
            {
                return this.adgangFormaalTypeKodeField;
            }
            set
            {
                this.adgangFormaalTypeKodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningPersonInddataType
    {
        
        private AbonnentAdgangStrukturType abonnentAdgangStrukturField;
        
        private AbonnentStrukturType abonnentStrukturField;
        
        private IndkomstOplysningPersonInddataTypeIndkomstOplysningValg indkomstOplysningValgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AbonnentAdgangStrukturType AbonnentAdgangStruktur
        {
            get
            {
                return this.abonnentAdgangStrukturField;
            }
            set
            {
                this.abonnentAdgangStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AbonnentStrukturType AbonnentStruktur
        {
            get
            {
                return this.abonnentStrukturField;
            }
            set
            {
                this.abonnentStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public IndkomstOplysningPersonInddataTypeIndkomstOplysningValg IndkomstOplysningValg
        {
            get
            {
                return this.indkomstOplysningValgField;
            }
            set
            {
                this.indkomstOplysningValgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningPersonInddataTypeIndkomstOplysningValg
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IndkomstForVirksomhedSamling", typeof(IndkomstOplysningPersonInddataTypeIndkomstOplysningValgIndkomstForVirksomhedSamling), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndkomstPersonSamling", typeof(IndkomstOplysningPersonInddataTypeIndkomstOplysningValgIndkomstPersonSamling), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningPersonInddataTypeIndkomstOplysningValgIndkomstForVirksomhedSamling
    {
        
        private VirksomhedIndkomstSoegeStrukturType[] virksomhedIndkomstSoegeStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VirksomhedIndkomstSoegeStruktur", Order=0)]
        public VirksomhedIndkomstSoegeStrukturType[] VirksomhedIndkomstSoegeStruktur
        {
            get
            {
                return this.virksomhedIndkomstSoegeStrukturField;
            }
            set
            {
                this.virksomhedIndkomstSoegeStrukturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningPersonInddataTypeIndkomstOplysningValgIndkomstPersonSamling
    {
        
        private PersonIndkomstSoegeStrukturType[] personIndkomstSoegeStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PersonIndkomstSoegeStruktur", Order=0)]
        public PersonIndkomstSoegeStrukturType[] PersonIndkomstSoegeStruktur
        {
            get
            {
                return this.personIndkomstSoegeStrukturField;
            }
            set
            {
                this.personIndkomstSoegeStrukturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kombit.dk/xml/schemas/kontekst/2017/01/01/")]
    public partial class RuteType
    {
        
        private string afsenderOrganisationField;
        
        private string afsenderItSystemInstansField;
        
        private string modtagerOrganisationField;
        
        private string modtagerItSystemInstansField;
        
        /// <remarks/>
        public string AfsenderOrganisation
        {
            get
            {
                return this.afsenderOrganisationField;
            }
            set
            {
                this.afsenderOrganisationField = value;
            }
        }
        
        /// <remarks/>
        public string AfsenderItSystemInstans
        {
            get
            {
                return this.afsenderItSystemInstansField;
            }
            set
            {
                this.afsenderItSystemInstansField = value;
            }
        }
        
        /// <remarks/>
        public string ModtagerOrganisation
        {
            get
            {
                return this.modtagerOrganisationField;
            }
            set
            {
                this.modtagerOrganisationField = value;
            }
        }
        
        /// <remarks/>
        public string ModtagerItSystemInstans
        {
            get
            {
                return this.modtagerItSystemInstansField;
            }
            set
            {
                this.modtagerItSystemInstansField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.kombit.dk/2017/01/01/")]
    public partial class IndkomstOplysningPersonHent_O : IndkomstOplysningPersonHent_OType
    {
        
        private string revisionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string revision
        {
            get
            {
                return this.revisionField;
            }
            set
            {
                this.revisionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IndkomstOplysningPersonHent
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kombit.dk/2017/01/01/", Order=0)]
        public ConnectedServices_SKATForwardEIndkomstService.IndkomstOplysningPersonHent_I IndkomstOplysningPersonHent_I;
        
        public IndkomstOplysningPersonHent()
        {
        }
        
        public IndkomstOplysningPersonHent(ConnectedServices_SKATForwardEIndkomstService.IndkomstOplysningPersonHent_I IndkomstOplysningPersonHent_I)
        {
            this.IndkomstOplysningPersonHent_I = IndkomstOplysningPersonHent_I;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IndkomstOplysningPersonHent1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kombit.dk/2017/01/01/", Order=0)]
        public ConnectedServices_SKATForwardEIndkomstService.IndkomstOplysningPersonHent_O IndkomstOplysningPersonHent_O;
        
        public IndkomstOplysningPersonHent1()
        {
        }
        
        public IndkomstOplysningPersonHent1(ConnectedServices_SKATForwardEIndkomstService.IndkomstOplysningPersonHent_O IndkomstOplysningPersonHent_O)
        {
            this.IndkomstOplysningPersonHent_O = IndkomstOplysningPersonHent_O;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    public interface SKATForwardEIndkomstServiceServicePortTypeChannel : ConnectedServices_SKATForwardEIndkomstService.SKATForwardEIndkomstServiceServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0-preview1.24619.5")]
    public partial class SKATForwardEIndkomstServiceServicePortTypeClient : System.ServiceModel.ClientBase<ConnectedServices_SKATForwardEIndkomstService.SKATForwardEIndkomstServiceServicePortType>, ConnectedServices_SKATForwardEIndkomstService.SKATForwardEIndkomstServiceServicePortType
    {
        
        public SKATForwardEIndkomstServiceServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConnectedServices_SKATForwardEIndkomstService.IndkomstOplysningPersonHent1> ConnectedServices_SKATForwardEIndkomstService.SKATForwardEIndkomstServiceServicePortType.SF0770_A_IndkomstoplysningerLaes_IndkomstoplysningerLaesAsync(ConnectedServices_SKATForwardEIndkomstService.IndkomstOplysningPersonHent request)
        {
            return base.Channel.SF0770_A_IndkomstoplysningerLaes_IndkomstoplysningerLaesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConnectedServices_SKATForwardEIndkomstService.IndkomstOplysningPersonHent1> SF0770_A_IndkomstoplysningerLaes_IndkomstoplysningerLaesAsync(ConnectedServices_SKATForwardEIndkomstService.IndkomstOplysningPersonHent_I IndkomstOplysningPersonHent_I)
        {
            ConnectedServices_SKATForwardEIndkomstService.IndkomstOplysningPersonHent inValue = new ConnectedServices_SKATForwardEIndkomstService.IndkomstOplysningPersonHent();
            inValue.IndkomstOplysningPersonHent_I = IndkomstOplysningPersonHent_I;
            return ((ConnectedServices_SKATForwardEIndkomstService.SKATForwardEIndkomstServiceServicePortType)(this)).SF0770_A_IndkomstoplysningerLaes_IndkomstoplysningerLaesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
    }
}
